/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class simulator_integration_AutopilotAdapter */

#ifndef _Included_simulator_integration_AutopilotAdapter
#define _Included_simulator_integration_AutopilotAdapter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     simulator_integration_AutopilotAdapter
 * Method:    set_timeIncrement
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_simulator_integration_AutopilotAdapter_set_1timeIncrement
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     simulator_integration_AutopilotAdapter
 * Method:    set_currentVelocity
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_simulator_integration_AutopilotAdapter_set_1currentVelocity
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     simulator_integration_AutopilotAdapter
 * Method:    set_currentGpsLat
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_simulator_integration_AutopilotAdapter_set_1currentGpsLat
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     simulator_integration_AutopilotAdapter
 * Method:    set_currentGpsLon
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_simulator_integration_AutopilotAdapter_set_1currentGpsLon
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     simulator_integration_AutopilotAdapter
 * Method:    set_compass
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_simulator_integration_AutopilotAdapter_set_1compass
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     simulator_integration_AutopilotAdapter
 * Method:    set_currentEngine
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_simulator_integration_AutopilotAdapter_set_1currentEngine
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     simulator_integration_AutopilotAdapter
 * Method:    set_currentSteering
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_simulator_integration_AutopilotAdapter_set_1currentSteering
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     simulator_integration_AutopilotAdapter
 * Method:    set_currentBrakes
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_simulator_integration_AutopilotAdapter_set_1currentBrakes
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     simulator_integration_AutopilotAdapter
 * Method:    set_goalNodeId
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_simulator_integration_AutopilotAdapter_set_1goalNodeId
  (JNIEnv *, jobject, jlong);

/*
 * Class:     simulator_integration_AutopilotAdapter
 * Method:    set_addNodes_length
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_simulator_integration_AutopilotAdapter_set_1addNodes_1length
  (JNIEnv *, jobject, jint);

/*
 * Class:     simulator_integration_AutopilotAdapter
 * Method:    set_addNodes_id
 * Signature: ([J)V
 */
JNIEXPORT void JNICALL Java_simulator_integration_AutopilotAdapter_set_1addNodes_1id
  (JNIEnv *, jobject, jlongArray);

/*
 * Class:     simulator_integration_AutopilotAdapter
 * Method:    set_addNodes_gpsLat
 * Signature: ([D)V
 */
JNIEXPORT void JNICALL Java_simulator_integration_AutopilotAdapter_set_1addNodes_1gpsLat
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     simulator_integration_AutopilotAdapter
 * Method:    set_addNodes_gpsLon
 * Signature: ([D)V
 */
JNIEXPORT void JNICALL Java_simulator_integration_AutopilotAdapter_set_1addNodes_1gpsLon
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     simulator_integration_AutopilotAdapter
 * Method:    set_removeNodes_length
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_simulator_integration_AutopilotAdapter_set_1removeNodes_1length
  (JNIEnv *, jobject, jint);

/*
 * Class:     simulator_integration_AutopilotAdapter
 * Method:    set_removeNodes_id
 * Signature: ([J)V
 */
JNIEXPORT void JNICALL Java_simulator_integration_AutopilotAdapter_set_1removeNodes_1id
  (JNIEnv *, jobject, jlongArray);

/*
 * Class:     simulator_integration_AutopilotAdapter
 * Method:    set_addOrUpdateEdges_length
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_simulator_integration_AutopilotAdapter_set_1addOrUpdateEdges_1length
  (JNIEnv *, jobject, jint);

/*
 * Class:     simulator_integration_AutopilotAdapter
 * Method:    set_addOrUpdateEdges_fromNodeId
 * Signature: ([J)V
 */
JNIEXPORT void JNICALL Java_simulator_integration_AutopilotAdapter_set_1addOrUpdateEdges_1fromNodeId
  (JNIEnv *, jobject, jlongArray);

/*
 * Class:     simulator_integration_AutopilotAdapter
 * Method:    set_addOrUpdateEdges_toNodeId
 * Signature: ([J)V
 */
JNIEXPORT void JNICALL Java_simulator_integration_AutopilotAdapter_set_1addOrUpdateEdges_1toNodeId
  (JNIEnv *, jobject, jlongArray);

/*
 * Class:     simulator_integration_AutopilotAdapter
 * Method:    set_addOrUpdateEdges_cost
 * Signature: ([D)V
 */
JNIEXPORT void JNICALL Java_simulator_integration_AutopilotAdapter_set_1addOrUpdateEdges_1cost
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     simulator_integration_AutopilotAdapter
 * Method:    set_removeEdges_length
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_simulator_integration_AutopilotAdapter_set_1removeEdges_1length
  (JNIEnv *, jobject, jint);

/*
 * Class:     simulator_integration_AutopilotAdapter
 * Method:    set_removeEdges_fromNodeId
 * Signature: ([J)V
 */
JNIEXPORT void JNICALL Java_simulator_integration_AutopilotAdapter_set_1removeEdges_1fromNodeId
  (JNIEnv *, jobject, jlongArray);

/*
 * Class:     simulator_integration_AutopilotAdapter
 * Method:    set_removeEdges_toNodeId
 * Signature: ([J)V
 */
JNIEXPORT void JNICALL Java_simulator_integration_AutopilotAdapter_set_1removeEdges_1toNodeId
  (JNIEnv *, jobject, jlongArray);

/*
 * Class:     simulator_integration_AutopilotAdapter
 * Method:    get_engine
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_simulator_integration_AutopilotAdapter_get_1engine
  (JNIEnv *, jobject);

/*
 * Class:     simulator_integration_AutopilotAdapter
 * Method:    get_steering
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_simulator_integration_AutopilotAdapter_get_1steering
  (JNIEnv *, jobject);

/*
 * Class:     simulator_integration_AutopilotAdapter
 * Method:    get_brakes
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_simulator_integration_AutopilotAdapter_get_1brakes
  (JNIEnv *, jobject);

/*
 * Class:     simulator_integration_AutopilotAdapter
 * Method:    exec
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_simulator_integration_AutopilotAdapter_exec
  (JNIEnv *, jobject);

/*
 * Class:     simulator_integration_AutopilotAdapter
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_simulator_integration_AutopilotAdapter_init
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
